behaviors:
  FlappyAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 1.0e-4
      beta: 5.0e-3 
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3 
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10_000_000 
    time_horizon: 128 
    summary_freq: 10000
    threaded: true
    